Ali/populate table
cse110-sp24-group14/warmup-exercise pull request #11
Opened 2024-04-22 02:25 UTC by a3alani

## Tracking Info

Resolves #9

## Changes

- I added a JS function in app.js that returns the tasks in order sorted by date.
- In index.html, I displayed the tasks in sorted order in a table. Note for that I used the code in script tags inside the HTML file, but the JS function could also be used by calling it and it will return the tasks ordered by date if needed.

## Testing

- I checked the return of the JS function by logging the output on the console and comparing the results to the expected output. It indeed returned the tasks in order sorted by date.

## Confirmation of Change

![Screenshot 2024-04-21 at 7 18 50 PM](https://github.com/cse110-sp24-group14/warmup-exercise/assets/103146838/79b3171c-aa71-4fe9-b7a4-c91676a24558)

2024-04-22 18:50 UTC, advaithm22 commented
I think the "Date" feature should be displayed in "month/day/year,  time" format, similar to what Edward did. Here is an example: 
<img width="317" alt="Screen Shot 2024-04-22 at 11 50 02 AM" src="https://github.com/cse110-sp24-group14/warmup-exercise/assets/80607809/cc48cffd-4dba-4755-a4c0-65140e43873b">

2024-04-24 00:11 UTC, brentonmdunn requested changes
Just a few small changes, otherwise looks great

2024-04-24 00:11 UTC, brentonmdunn commented on app.js
> +      console.log("sorted parsed dates", parsed_dates);
Can you remove the `console.log`?

2024-04-24 00:11 UTC, brentonmdunn commented on app.js
> + return data type example: [{},{},{},{},{},{}]
Probably keep the header on top but remove the sample json data below

2024-04-24 00:11 UTC, brentonmdunn commented on index.html
> +          <!-- <th>ID</th>
remove comments

2024-04-24 00:11 UTC, brentonmdunn commented on index.html
> +              // title_val: task.title,
remove comments (I know I was the one that commented it out but I just wanted to make sure I didn't break anything)

2024-04-24 00:11 UTC, brentonmdunn commented on index.html
> +          console.log("sorted parsed dates", parsed_dates);
remove `console.log`

2024-04-24 00:11 UTC, brentonmdunn commented on index.html
> +          <th>Due Date</th>
Can you flip the columns so that due date is column on the left and task is column on the right?

2024-04-26 06:41 UTC, advaithm22 approved these changes

2024-04-26 06:58 UTC, merged